version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3307
      DB_DATABASE: controle_fornecedor
      DB_USERNAME: root
      DB_PASSWORD: root
      SERVER_NAME: localhost
    command: >
      bash -c "a2enmod rewrite &&
               service apache2 restart &&
               apache2-foreground"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: controle_fornecedor
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
