services:
    mysql-db:
        image: mysql:8.0
        restart: unless-stopped
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: controle_fornecedor
        volumes:
            - ./mysql-data:/var/lib/mysql
        ports:
            - "3307:3306"
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-proot'
            retries: 3
            timeout: 5s

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend
        restart: unless-stopped
        volumes:
            - .:/var/www/html/api-rest-laravel-docker/storage
        environment:
            DB_HOST: db
            #DB_PORT: 3306
            #MYSQL_ROOT_HOST: '%'
            #DB_DATABASE: '${DB_DATABASE}'
            #DB_USERNAME: '${DB_USERNAME}'
            #DB_PASSWORD: '${DB_PASSWORD}'

            DB_PORT: 3306
            DB_DATABASE: controle_fornecedor
            DB_USERNAME: root
            DB_PASSWORD: root
        depends_on:
            - db
        ports:
            - "8000:80"  # 8000: Porta no host (servidor Linux) 80: Porta no contêiner.
