services:
    mysql-db:
        image: mysql:8.0
        restart: unless-stopped
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
        volumes:
            - ./mysql-data:/var/lib/mysql
        ports:
            - "3307:3306"
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-proot'
            retries: 3
            timeout: 5s

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend
        restart: unless-stopped
        volumes:
            - .:/var/www/html/api-rest-laravel-docker
        environment:
            DB_HOST: mysql-db
            DB_PORT: 3306
            DB_DATABASE: '${DB_DATABASE}'
            DB_USERNAME: '${DB_USERNAME}'
            DB_PASSWORD: '${DB_PASSWORD}'
        depends_on:
            - mysql-db
        ports:
            - "8000:82"  # 8000: Porta no host (servidor Linux) 82 Porta no contêiner.
