services:
    mysql-db:
        image: mysql:8.0
        restart: unless-stopped
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: controle_fornecedor
        volumes:
            - ./mysql-data:/var/lib/mysql
        ports:
            - "3307:3306"
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-proot'
            retries: 3
            timeout: 5s

    backend:
        build: .
        container_name: backend
        restart: unless-stopped
        volumes:
            - .:/var/www/html/teste-dev-php/storage
        environment:
            DB_HOST: mysql-db
            DB_PORT: 3306
            DB_DATABASE: '${DB_DATABASE}'
            DB_USERNAME: '${DB_USERNAME}'
            DB_PASSWORD: '${DB_PASSWORD}'
        depends_on:
            - mysql-db
        ports:
            - "8000:80"
