services:
    mysql-db:
        image: mysql:5.7
        restart: unless-stopped
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: controle_fornecedor
        volumes:
            - ./mysql-data:/var/lib/mysql
        ports:
            - "3307:3306"  # Porta 3307 no host aponta para a 3306 no contêiner

    backend:
        build: .
        container_name: backend
        restart: unless-stopped
        volumes:
            - .:/var/www/html/teste-dev-php
        environment:
            DB_HOST: mysql-db
            DB_PORT: 3306
            DB_DATABASE: controle_fornecedor
            DB_USERNAME: root
            DB_PASSWORD: root
            DB_CONNECTION: mysql
        depends_on:
            - mysql-db
        ports:
            - 8000:80
