services:

    mysql-db:
        image: mysql:5.7
        restart: unless-stopped
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: my_db
        volumes:
            - ./mysql-data:/var/lib/mysql
        ports:
            - 3306:3306

    backend:
        build: .
        container_name: backend
        restart: unless-stopped
        volumes:
            - .:/var/www/html

        environment:
            DB_HOST: mysql-db
            DB_PORT: 3306
            DB_DATABASE: my_db
            DB_USERNAME: root
            DB_PASSWORD: root
            DB_CONNECTION: mysql

        depends_on:
            - mysql-db
        ports:
            - 8000:80
