name: Deploy

on:
  push:
    branches:
      - main
  pull_request:

    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        #variaveis de ambiente
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port:  ${{ secrets.PORT }}
        key:  ${{ secrets.SSHKEY }}

        script: /var/www/html/api-rest-laravel-docker$ ./.scripts/deploy.sh
