name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    #runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSHKEY }}

    - name: Fix SSH Key Permissions
      run: |
        echo "${{ secrets.SSHKEY }}" > key
        chmod 600 key

    - name: Run deployment script on WSL
      run: |
        wsl bash -c "cd /var/www/html/api-rest-laravel-docker && ./.scripts/deploy.sh"
