name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        # Definindo o diretório temporário corretamente para Windows
        $tempDir = "C:\temp"
        if (-not (Test-Path $tempDir)) {
          New-Item -Path $tempDir -ItemType Directory
        }

        # Decodificando e salvando a chave SSH no diretório temporário
        echo "${{ secrets.SSHKEY_BASE64 }}" | base64 -d > $tempDir\id_rsa
        chmod 600 $tempDir\id_rsa
        eval $(ssh-agent -s)
        ssh-add $tempDir\id_rsa

        mkdir -p C:\Users\runneradmin\.ssh
        touch C:\Users\runneradmin\.ssh\config
        touch C:\Users\runneradmin\.ssh\known_hosts
        chmod -R 400 C:\Users\runneradmin\.ssh

        # Substitua pelo IP real ou variável
        $EC2_PUBLIC_IP = "your.ec2.public.ip"  # Substitua com o IP real
        ssh-keyscan -H $EC2_PUBLIC_IP | Out-File -Append -FilePath C:\Users\runneradmin\.ssh\known_hosts

    - name: Run deployment script on WSL
      run: |
        wsl bash -c "cd /var/www/html/api-rest-laravel-docker && ./.scripts/deploy.sh"
