name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        # Definindo o diretório temporário corretamente para Windows
        $tempDir = "C:\temp"
        if (-not (Test-Path $tempDir)) {
          New-Item -Path $tempDir -ItemType Directory
        }

        # Criando o diretório .ssh se não existir
        mkdir -p C:\Users\runneradmin\.ssh

        # Copiando a chave SSH diretamente do GitHub Secrets para o arquivo id_rsa
        $env:SSH_PRIVATE_KEY = "${{ secrets.SSH_PRIVATE_KEY }}"
        Set-Content -Path "C:\Users\runneradmin\.ssh\id_rsa" -Value $env:SSH_PRIVATE_KEY
        chmod 600 C:\Users\runneradmin\.ssh\id_rsa

        # Garantindo que o arquivo known_hosts exista
        touch C:\Users\runneradmin\.ssh\known_hosts

        # Substitua pelo IP real ou variável
        $EC2_PUBLIC_IP = "${{ secrets.EC2_PUBLIC_IP }}"  # Substitua com o IP real
        ssh-keyscan -H $EC2_PUBLIC_IP | Out-File -Append -FilePath C:\Users\runneradmin\.ssh\known_hosts

    - name: Run deployment script on WSL
      run: |
        wsl bash -c "cd /var/www/html/api-rest-laravel-docker && ./.scripts/deploy.sh"
