jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "${{ secrets.SSHKEY_BASE64 }}" | base64 -d > /tmp/id_rsa
        chmod 600 /tmp/id_rsa
