name: update
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: centos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run deployment script on CentOS (corrected user and path)
        run: |
          ssh centos@${{ secrets.HOST }} 'sudo -E sh -c "cd /var/www/html/my-laravel-app && git pull origin main"'

