name: update
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

      with:
        host: ${{secrets.HOST}}
        key: ${{ secrets.SSHKEY }}
        username: ${{secrets.USERNAME}}
        port: ${{secrets.PORT}}
      run: |
        wsl bash -c "cd /var/www/html/api-rest-laravel-docker && ./.scripts/update.sh"
